### PR TITLE
Moved the action from the gsd-datatbase to gsd-tools

### PR DESCRIPTION
**Pull request by raphaelahrens**
Moved the script to the gsd-tools repo as suggested by this comment https://github.com/cloudsecurityalliance/gsd-database/pull/2295#issuecomment-1069754624 .

If the PR is accepted the actions can be used as follows

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: deletion-check
        uses: cloudsecurityalliance/gsd-tools/actions/deletion-check
      - name: json-check
        uses: cloudsecurityalliance/gsd-tools/actions/json-check
```
See the full example https://github.com/raphaelahrens/gsd-database/blob/action_test/.github/workflows/json.yml

Here an example output from a commit with a broken json file https://github.com/raphaelahrens/gsd-database/runs/5979488733?check_suite_focus=true

Here the output from a deletion https://github.com/raphaelahrens/gsd-database/runs/5971825263?check_suite_focus=true

### CODE REVIEW

**Comment by raphaelahrens** [comment]
Is there a problem with the PR?

**Comment by joshbressers** [comment]
@raphaelahrens Apologies, this has been on my list and other things keep coming up. I'll do my best to look at it today

**Comment by raphaelahrens** [comment]
No need to apologies. I just want to know if this is useful or if I am wasting everyone's time.
Because I also build a check for the formatting of the GSD-files and began looking into URL extraction, which builds on this PR.

But please don't stress yourself and take the time you need.

**Comment by joshbressers** [comment]
This looks amazing!

Thank you so much @raphaelahrens

**Comment by joshbressers** [comment]
@raphaelahrens I would love it if you could submit the PR to the database to enable this. If not I'll do it when I find some free time

**Comment by oswalpalash** [comment]
Thanks @raphaelahrens! This is great.

**Pull request merged**
